### ISSUE TITLE
ipfs.add + globSource + many files will freeze

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfs#2943]
```ts
let ret = await addDirectoryToIPFS(ipfs, `target path`, {
			options: {
				pin:  false,
				//progress: createProgressBar,
			},
			globSourceOptions: {
				hidden: true,
			},
		});

		console.dir(ret.files.length);
		console.dir(ret.root.cid.toString());
```

use v1 will can't see any thing and freeze
use v2 will see some logs, but after many runs will freeze

both can't finish job

test file
https://ipfs.io/ipfs/QmQtUGvQnYv2ZDw5GdRsaMXqjsYGp3h74BwoFHRRSFiWRZ?filename=.cache.7z

v1
```ts
export async function addDirectoryToIPFS(ipfs: IIPFSFileApi, targetDirPath: string, {
	options,
	globSourceOptions,
}: {
	options?: IIPFSFileApiAddOptions,
	globSourceOptions?: IGlobSourceOptions,
} = {})
{
	let files: IIPFSFileApiAddReturnEntry[] = [];

	for await (const file of ipfs.add(globSource(targetDirPath, {
		recursive: true,
		...globSourceOptions,
	}), options))
	{
		console.log(file)
		files.push(file);
	}

	const root = files[files.length - 1]

	return {
		targetDirPath,
		root,
		files,
	}
}
```

v2
```ts
export async function addDirectoryToIPFS(ipfs: IIPFSFileApi, targetDirPath: string, {
	options,
	globSourceOptions,
}: {
	options?: IIPFSFileApiAddOptions,
	globSourceOptions?: IGlobSourceOptions,
} = {})
{

	const stream = globSource(targetDirPath, {
		recursive: true,
		...globSourceOptions,
	})

	let files: IIPFSFileApiAddReturnEntry[] = [];
	let root: IIPFSFileApiAddReturnEntry;

	let i = 0;

	// @ts-ignore
	for await (const file of ipfs.add(stream, options))
	{
		if ((i++ % 100) === 0)
		{
			console.dir(file.path)
			console.log(file.cid.toString());
			//console.dir(root = file)
		}

		root = file;
	}

	return {
		targetDirPath,
		root,
		files: {
			length: i,
		},
	}
}
```

**Comment by bluelovers** [comment]
over http

**Comment by achingbrain** [comment]
Is the daemon running in the background when you use the CLI?

**Comment by bluelovers** [comment]
yes

**Comment by bluelovers** [comment]
video
https://ipfs.io/ipfs/QmeaxfayZPFnhV8L6VpkfDYv2fTtN6BRsAYdXKHuGEZQZi?filename=bandicam%202020-03-25%2002-56-27-468.avi

first delay is by search files,

but............

after upload to 2x % is freezed, not more print any message

**Comment by achingbrain** [comment]
The next release will included reworked multipart requests and it should resolve this issue (hopefully later this week) - previously in order to use [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) requests we had to [buffer up every file that's being uploaded](https://github.com/ipfs/js-ipfs/blob/bfba76748b8aabc0d66768009ff6f4adb24ff439/packages/ipfs-http-client/src/add/form-data.js) but now we create a [streaming multipart request](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/src/lib/multipart-request.js).

This will work for node, but for the browser it will be fixed when they support streaming uploads - for more see https://github.com/ipfs/js-ipfs/issues/2838

**Comment by bluelovers** [comment]
v3 

> freeze at first file

```ts
import getStream from 'get-stream';

export async function addDirectoryToIPFS(ipfs: IIPFSFilesApi, targetDirPath: string, {
	options,
	globSourceOptions,
}: {
	options?: IIPFSFileApiAddOptions,
	globSourceOptions?: IGlobSourceOptions,
} = {})
{

	const stream = globSource(targetDirPath, {
		recursive: true,
		...globSourceOptions,
	})

	let i = 0;
	let cid;

	for await (const entry of stream)
	{
		console.dir(entry.path)

		if (entry.content)
		{
			let buf = await getStream.buffer(entry.content)

			await ipfs.files.write(entry.path, buf, {
				create: true,
				parents: true,
				mode: entry.mode,
				mtime: entry.mtime,
			})

			i++;

			if ((i % 100) === 0)
			{
				const cid = await ipfs.files.flush()

				console.log(cid.toString())
			}
		}

	}

	cid = await ipfs.files.flush()

	return {
		targetDirPath,
		root: {
			cid,
		},
		files: {
			length: i,
		},
	}
}
```

**Comment by bluelovers** [comment]
when i use v3 for upload, it still will freeze after upload many file

v3
```ts
export async function addDirectoryToIPFS(ipfs: IIPFSFilesApi & IIPFSFilesApi, targetDirPath: string, {
	options,
	globSourceOptions,
	ignoreExists,
}: {
	options?: IIPFSFileApiAddOptions,
	globSourceOptions?: IGlobSourceOptions,
	ignoreExists?: boolean,
} = {})
{

	const stream = globSource(targetDirPath, {
		recursive: true,
		...globSourceOptions,
	})

	let i = 0;
	let cid;

	ignoreExists = !!ignoreExists;

	for await (const entry of stream)
	{
		if (entry.content)
		{
			if (ignoreExists === true && await ipfsFilesExists(ipfs, entry.path))
			{
				console.gray.debug(entry.path)
				continue;
			}

			console.debug(entry.path)

			let buf = await getStream.buffer(entry.content)

			await ipfs.files.write(entry.path, buf, {
				create: true,
				parents: true,
				mode: entry.mode,
				mtime: entry.mtime,
			})

			i++;

			if ((i % 100) === 0)
			{
				const cid = await ipfs.files.flush()

				console.debug(cid.toString())
			}
		}
		else
		{
			console.debug(entry.path)
		}

	}

	cid = await ipfs.files.flush()

	return {
		targetDirPath,
		root: {
			cid,
		},
		files: {
			length: i,
		},
	}
}
```

**Comment by bluelovers** [comment]
at v4 is same, it still freeze after update many files

so i think maybe is something happen in ipfs daemon

```ts
export async function addDirectoryToIPFS(ipfs: IIPFSFilesApi & IIPFSFilesApi, targetDirPath: string, {
	options,
	globSourceOptions,
	ignoreExists,
}: {
	options?: IIPFSFileApiAddOptions,
	globSourceOptions?: IGlobSourceOptions,
	ignoreExists?: boolean,
} = {})
{
	let i = 0;
	let cid;

	ignoreExists = !!ignoreExists;

	const rootPath = '/' + path.basename(targetDirPath) + '/';

	for await (let filename of FastGlob.stream([
		'**/*',
		'**/*.txt',
	], {
		cwd: targetDirPath,
		onlyFiles: true,
		//deep: Infinity,
	}))
	{
		filename = filename.toString();

		//console.dir(filename)

		let entry = {
			path: rootPath + filename,
			// @ts-ignore
			//content: createReadStream(path.join(targetDirPath, filename)),
			mode: undefined,
			mtime: undefined,
		}

		if (ignoreExists === true && await ipfsFilesExists(ipfs, entry.path))
		{
			console.gray.debug(entry.path)
			continue;
		}

		console.debug(entry.path)

		let buf = await readFile(path.join(targetDirPath, filename))

		await ipfs.files.write(entry.path, buf, {
			create: true,
			parents: true,
			mode: entry.mode,
			mtime: entry.mtime,
		})

		i++;

		if ((i % 100) === 0)
		{
			const cid = await ipfs.files.flush()

			console.success(cid.toString())
		}

	}

	cid = await ipfs.files.flush()

	return {
		targetDirPath,
		root: {
			cid,
		},
		files: {
			length: i,
		},
	}
}
```

**Comment by bluelovers** [comment]
when it freeze

webui can't connect to daemon

![image](https://user-images.githubusercontent.com/167966/77520674-84d9e180-6ebc-11ea-90e4-f045104a5447.png)

and daemon is still live in console

![image](https://user-images.githubusercontent.com/167966/77520646-7986b600-6ebc-11ea-8795-21ed48755355.png)
